import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import html2canvas from "html2canvas-pro";
import { format } from "date-fns";

// ============================================================
// CONSTANTS
// ============================================================
const MARGIN = 25.4; // 1 inch in mm
const PAGE_W = 210; // A4 width mm
const PAGE_H = 297; // A4 height mm
const CONTENT_W = PAGE_W - MARGIN * 2; // usable width
const CHART_FULL_H = 75; // ~3 inches for full-width trend charts
const CHART_HALF_H = 75; // ~3 inches for half-width charts
const FONT = "helvetica"; // closest to Arial in jsPDF built-in fonts
const FOOTER_H = 15; // reserved footer space

const COLORS = {
  primary: [22, 163, 74], // BrewGuard green
  dark: [17, 24, 39],
  gray: [107, 114, 128],
  lightGray: [243, 244, 246],
  white: [255, 255, 255],
  tableStripe: [249, 250, 251],
};

// ============================================================
// HELPERS
// ============================================================
function addFooters(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont(FONT, "normal");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.gray);
    doc.text("System Generated Document - Confidential", MARGIN, PAGE_H - 10);
    doc.text(`Page ${i} of ${pageCount}`, PAGE_W - MARGIN, PAGE_H - 10, {
      align: "right",
    });
    // Footer separator line
    doc.setDrawColor(...COLORS.lightGray);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, PAGE_H - 15, PAGE_W - MARGIN, PAGE_H - 15);
  }
}

function drawHeader(doc, title, dateRange, userName) {
  let y = MARGIN;

  // Logo text
  doc.setFont(FONT, "bold");
  doc.setFontSize(16);
  doc.setTextColor(...COLORS.primary);
  doc.text("BrewGuard", MARGIN, y + 5);

  // Date & user info
  doc.setFont(FONT, "normal");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.gray);
  const dateGen = format(new Date(), "MMMM d, yyyy");
  doc.text(`Date Generated: ${dateGen}`, PAGE_W - MARGIN, y, {
    align: "right",
  });
  doc.text(`Generated By: ${userName}`, PAGE_W - MARGIN, y + 5, {
    align: "right",
  });

  // Report period
  const periodText = `Report Period: ${format(dateRange.from, "MMM d, yyyy")} – ${format(dateRange.to, "MMM d, yyyy")}`;
  doc.text(periodText, PAGE_W - MARGIN, y + 10, { align: "right" });

  y += 20;

  // Header separator line
  doc.setDrawColor(...COLORS.lightGray);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);

  y += 8;

  // Report title
  doc.setFont(FONT, "bold");
  doc.setFontSize(20);
  doc.setTextColor(...COLORS.dark);
  doc.text(title, PAGE_W / 2, y, { align: "center" });

  return y + 12;
}

function drawSectionHeader(doc, text, y) {
  ensureSpace(doc, y, 20);
  doc.setFont(FONT, "bold");
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.dark);
  doc.text(text, MARGIN, y);
  return y + 8;
}

function drawSummaryCards(doc, cards, y) {
  ensureSpace(doc, y, 30);

  const cardW = (CONTENT_W - 6) / 4; // 4 cards with 2mm gaps
  const cardH = 22;

  cards.forEach((card, i) => {
    const x = MARGIN + i * (cardW + 2);

    // Card background
    doc.setFillColor(...COLORS.lightGray);
    doc.roundedRect(x, y, cardW, cardH, 2, 2, "F");

    // Card title
    doc.setFont(FONT, "normal");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.gray);
    doc.text(card.title, x + 3, y + 6);

    // Card value
    doc.setFont(FONT, "bold");
    doc.setFontSize(14);
    doc.setTextColor(...COLORS.dark);
    doc.text(String(card.value), x + 3, y + 14);

    // Change indicator
    if (card.change && card.change.changePercent !== undefined) {
      const pct = card.change.changePercent;
      const symbol = pct > 0 ? "▲" : pct < 0 ? "▼" : "–";
      const color =
        pct > 0 ? [22, 163, 74] : pct < 0 ? [239, 68, 68] : COLORS.gray;
      doc.setFont(FONT, "normal");
      doc.setFontSize(7);
      doc.setTextColor(...color);
      doc.text(`${symbol} ${pct > 0 ? "+" : ""}${pct}%`, x + 3, y + 19);
    }
  });

  return y + cardH + 6;
}

function ensureSpace(doc, currentY, neededH) {
  if (currentY + neededH > PAGE_H - MARGIN - FOOTER_H) {
    doc.addPage();
    return MARGIN;
  }
  return currentY;
}

async function captureChart(elementId) {
  const el = document.getElementById(elementId);
  if (!el) return null;
  const canvas = await html2canvas(el, {
    scale: 2,
    useCORS: true,
    logging: false,
    backgroundColor: "#ffffff",
  });
  return canvas.toDataURL("image/png");
}

function addChartImage(doc, imgData, x, y, w, h) {
  y = ensureSpace(doc, y, h + 5);
  if (imgData) {
    doc.addImage(imgData, "PNG", x, y, w, h);
  }
  return y + h + 6;
}

function addTable(doc, columns, rows, startY) {
  startY = ensureSpace(doc, startY, 30);
  autoTable(doc, {
    startY,
    margin: { left: MARGIN, right: MARGIN },
    head: [columns.map((c) => c.header)],
    body: rows,
    theme: "grid",
    styles: {
      font: FONT,
      fontSize: 10,
      cellPadding: 2.5,
      textColor: COLORS.dark,
      lineColor: [229, 231, 235],
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: COLORS.lightGray,
      textColor: COLORS.dark,
      fontStyle: "bold",
      fontSize: 10,
    },
    alternateRowStyles: {
      fillColor: COLORS.tableStripe,
    },
    columnStyles: columns.reduce((acc, col, i) => {
      if (col.align) acc[i] = { halign: col.align };
      return acc;
    }, {}),
    didDrawPage: () => {},
  });
  return doc.lastAutoTable.finalY + 8;
}

// ============================================================
// PROCUREMENT PDF
// ============================================================
export async function generateProcurementPdf(data, dateRange, userName) {
  const doc = new jsPDF("p", "mm", "a4");
  let y = drawHeader(
    doc,
    "Procurement Performance Report",
    dateRange,
    userName,
  );

  // Summary cards
  y = drawSummaryCards(
    doc,
    [
      {
        title: "Total Purchase Orders",
        value: data.totalPurchaseOrders ?? 0,
        change: data.purchaseOrdersChange,
      },
      {
        title: "Total Shipments",
        value: data.totalShipments ?? 0,
        change: data.shipmentsChange,
      },
      {
        title: "Items Received",
        value: `${Math.round(data.totalItemsReceived ?? 0)} kg`,
        change: data.volumeChange,
      },
      {
        title: "On-Time Delivery",
        value: `${data.onTimeDeliveryRate ?? 0}%`,
        change: data.onTimeChange,
      },
    ],
    y,
  );

  // Chart: Procurement Volume Trend (full width)
  y = drawSectionHeader(doc, "Procurement Volume Trend", y);
  const volumeImg = await captureChart("chart-procurement-volume");
  y = addChartImage(doc, volumeImg, MARGIN, y, CONTENT_W, CHART_FULL_H);

  // Table: Volume Trend Data
  if (data.monthlyProcurementVolume?.length) {
    y = drawSectionHeader(doc, "Volume Trend Data", y);
    y = addTable(
      doc,
      [
        { header: "Period", align: "left" },
        { header: "Volume (kg)", align: "right" },
      ],
      data.monthlyProcurementVolume.map((d) => [d.label, d.volume.toFixed(1)]),
      y,
    );
  }

  // Charts: Top Items + Supplier Performance (side by side)
  y = drawSectionHeader(doc, "Top Items & Supplier Performance", y);
  const halfW = (CONTENT_W - 4) / 2;
  const topItemsImg = await captureChart("chart-procurement-top-items");
  const supplierImg = await captureChart("chart-procurement-supplier-perf");
  y = ensureSpace(doc, y, CHART_HALF_H + 5);
  if (topItemsImg)
    doc.addImage(topItemsImg, "PNG", MARGIN, y, halfW, CHART_HALF_H);
  if (supplierImg)
    doc.addImage(
      supplierImg,
      "PNG",
      MARGIN + halfW + 4,
      y,
      halfW,
      CHART_HALF_H,
    );
  y += CHART_HALF_H + 6;

  // Table: Top Items
  if (data.topItemsByVolume?.length) {
    y = drawSectionHeader(doc, "Top Items by Volume", y);
    y = addTable(
      doc,
      [
        { header: "Item Name", align: "left" },
        { header: "Total Quantity (kg)", align: "right" },
      ],
      data.topItemsByVolume.map((d) => [
        d.itemName,
        d.totalQuantity.toFixed(1),
      ]),
      y,
    );
  }

  // Table: Supplier Delivery Performance
  if (data.supplierPerformance?.length) {
    y = drawSectionHeader(doc, "Supplier Delivery Performance", y);
    y = addTable(
      doc,
      [
        { header: "Supplier", align: "left" },
        { header: "Total Shipments", align: "right" },
        { header: "On-Time", align: "right" },
        { header: "On-Time Rate (%)", align: "right" },
      ],
      data.supplierPerformance.map((d) => [
        d.supplierName,
        String(d.totalShipments),
        String(d.onTimeShipments),
        `${d.onTimeRate}%`,
      ]),
      y,
    );
  }

  addFooters(doc);
  doc.save(buildFileName("Procurement", dateRange));
}

// ============================================================
// QUALITY PDF
// ============================================================
export async function generateQualityPdf(data, dateRange, userName) {
  const doc = new jsPDF("p", "mm", "a4");
  let y = drawHeader(doc, "Quality Compliance Report", dateRange, userName);

  y = drawSummaryCards(
    doc,
    [
      {
        title: "Total Inspections",
        value: data.totalInspections ?? 0,
        change: data.inspectionsChange,
      },
      {
        title: "Pass Rate",
        value: `${data.passRate ?? 0}%`,
        change: data.passRateChange,
      },
      {
        title: "Avg. Cupping Score",
        value: data.avgCuppingScore ?? 0,
        change: data.cuppingChange,
      },
      {
        title: "Avg. Turnaround",
        value: `${data.avgTurnaroundHours ?? 0} hrs`,
        change: data.turnaroundChange,
      },
    ],
    y,
  );

  // Chart: Pass Rate Trend (full width)
  y = drawSectionHeader(doc, "Pass Rate Trend", y);
  const passRateImg = await captureChart("chart-quality-pass-rate");
  y = addChartImage(doc, passRateImg, MARGIN, y, CONTENT_W, CHART_FULL_H);

  // Table: Pass Rate Data
  if (data.monthlyPassRates?.length) {
    y = drawSectionHeader(doc, "Pass Rate Data", y);
    y = addTable(
      doc,
      [
        { header: "Period", align: "left" },
        { header: "Pass Rate (%)", align: "right" },
      ],
      data.monthlyPassRates.map((d) => [d.label, `${d.passRate}%`]),
      y,
    );
  }

  // Table: Supplier Consistency
  if (data.supplierConsistency?.length) {
    y = drawSectionHeader(doc, "Supplier Consistency", y);
    y = addTable(
      doc,
      [
        { header: "Supplier", align: "left" },
        { header: "Inspections", align: "right" },
        { header: "Pass Rate (%)", align: "right" },
        { header: "Avg. Cupping", align: "right" },
      ],
      data.supplierConsistency.map((d) => [
        d.supplierName,
        String(d.totalInspections),
        `${d.passRate}%`,
        String(d.avgCuppingScore),
      ]),
      y,
    );
  }

  addFooters(doc);
  doc.save(buildFileName("Quality", dateRange));
}

// ============================================================
// PRODUCTION PDF
// ============================================================
export async function generateProductionPdf(data, dateRange, userName) {
  const doc = new jsPDF("p", "mm", "a4");
  let y = drawHeader(doc, "Production Quality Report", dateRange, userName);

  y = drawSummaryCards(
    doc,
    [
      {
        title: "Total CAPAs",
        value: data.totalCapas ?? 0,
        change: data.capasChange,
      },
      {
        title: "Avg. Resolution",
        value: `${data.avgResolutionDays ?? 0} days`,
        change: data.resolutionChange,
      },
      {
        title: "Completion Rate",
        value: `${data.actionPlanCompletionRate ?? 0}%`,
        change: data.completionChange,
      },
      {
        title: "Overdue Plans",
        value: data.overdueActionPlans ?? 0,
        change: data.overdueChange,
      },
    ],
    y,
  );

  // Charts: NCR Severity + Action Plan Status (side by side)
  y = drawSectionHeader(doc, "NCR Severity & Action Plan Status", y);
  const halfW = (CONTENT_W - 4) / 2;
  const severityImg = await captureChart("chart-production-ncr-severity");
  const statusImg = await captureChart("chart-production-action-status");
  y = ensureSpace(doc, y, CHART_HALF_H + 5);
  if (severityImg)
    doc.addImage(severityImg, "PNG", MARGIN, y, halfW, CHART_HALF_H);
  if (statusImg)
    doc.addImage(statusImg, "PNG", MARGIN + halfW + 4, y, halfW, CHART_HALF_H);
  y += CHART_HALF_H + 6;

  // Charts: NCR Trend + Top Defects (side by side)
  y = drawSectionHeader(doc, "NCR Trend & Top Recurring Defects", y);
  const ncrTrendImg = await captureChart("chart-production-ncr-trend");
  const defectsImg = await captureChart("chart-production-top-defects");
  y = ensureSpace(doc, y, CHART_HALF_H + 5);
  if (ncrTrendImg)
    doc.addImage(ncrTrendImg, "PNG", MARGIN, y, halfW, CHART_HALF_H);
  if (defectsImg)
    doc.addImage(defectsImg, "PNG", MARGIN + halfW + 4, y, halfW, CHART_HALF_H);
  y += CHART_HALF_H + 6;

  // Table: NCR Severity Breakdown
  if (data.ncrSeverityBreakdown?.length) {
    y = drawSectionHeader(doc, "NCR Severity Breakdown", y);
    y = addTable(
      doc,
      [
        { header: "Severity", align: "left" },
        { header: "Count", align: "right" },
      ],
      data.ncrSeverityBreakdown.map((d) => [d.severity, String(d.count)]),
      y,
    );
  }

  // Table: Action Plan Status
  if (data.actionPlanStatusBreakdown?.length) {
    y = drawSectionHeader(doc, "Action Plan Status", y);
    y = addTable(
      doc,
      [
        { header: "Status", align: "left" },
        { header: "Count", align: "right" },
      ],
      data.actionPlanStatusBreakdown.map((d) => [d.status, String(d.count)]),
      y,
    );
  }

  // Table: Top Recurring Defects
  if (data.topRecurringDefects?.length) {
    y = drawSectionHeader(doc, "Top Recurring Defects", y);
    y = addTable(
      doc,
      [
        { header: "Defect Description", align: "left" },
        { header: "Severity", align: "left" },
        { header: "Count", align: "right" },
      ],
      data.topRecurringDefects.map((d) => [
        d.defectDescription,
        d.severity,
        String(d.count),
      ]),
      y,
    );
  }

  addFooters(doc);
  doc.save(buildFileName("Production", dateRange));
}

// ============================================================
// FILE NAME
// ============================================================
function buildFileName(reportType, dateRange) {
  const from = format(dateRange.from, "yyyy-MM-dd");
  const to = format(dateRange.to, "yyyy-MM-dd");
  return `BrewGuard-${reportType}-Report-${from}-to-${to}.pdf`;
}
