import React from "react";
import { format } from "date-fns";

import { StatCard } from "./StatCard";
import { GlobalPassRateChart } from "./GlobalPassRateChart";
import { StockDistributionChart } from "./StockDistributionChart";
import { SupplierLeaderboardChart } from "./SupplierLeaderboardChart";
import { AlertTriangle, Activity, CheckCircle, Users } from "lucide-react";

export const AdminReportTemplate = React.forwardRef(({ stats, user }, ref) => {
  if (!stats) return null;

  const currentDate = format(new Date(), "PPpp");

  return (
    <div
      ref={ref}
      style={{
        position: "absolute",
        top: "-9999px",
        left: "-9999px",
        width: "210mm",
        minHeight: "297mm",
        backgroundColor: "white",
        color: "black",
        padding: "20mm",
        boxSizing: "border-box",
        fontFamily: "Arial, sans-serif",
      }}
      className="pdf-report-container"
    >
      {/* Header section */}
      <div className="flex justify-between items-start border-b-2 border-slate-200 pb-6 mb-8">
        <div className="flex items-center gap-4">
          <img
            src="/BrewGuard-transparent.png"
            alt="BrewGuard Logo"
            style={{ width: "80px", height: "auto" }}
          />
          <div>
            <h1 className="text-3xl font-bold text-slate-900 tracking-tight">
              BrewGuard Admin Report
            </h1>
            <p className="text-slate-500 font-medium mt-1">
              Comprehensive System Overview
            </p>
          </div>
        </div>
        <div className="text-right flex flex-col items-end">
          <p className="text-sm font-semibold text-slate-700">Generated By:</p>
          <p className="text-sm text-slate-600">
            {user?.firstName} {user?.lastName}
          </p>
          <p className="text-sm text-slate-600">
            {user?.role} - {user?.branchName || "Main Branch"}
          </p>
          <p className="text-sm text-slate-500 mt-2">{currentDate}</p>
        </div>
      </div>

      {/* Stats Section */}
      <div className="mb-8">
        <h2 className="text-xl font-bold text-slate-800 mb-4 border-b pb-2">
          Key Performance Indicators
        </h2>
        <div className="grid grid-cols-4 gap-4">
          {/* Simple stat cards for print */}
          <div className="p-4 rounded-lg border border-slate-200 bg-slate-50">
            <div className="flex items-center gap-2 mb-2 text-slate-600">
              <AlertTriangle className="h-5 w-5 text-amber-500" />
              <span className="font-semibold text-sm">Critical Alerts</span>
            </div>
            <div className="text-2xl font-bold text-slate-900">
              {stats?.criticalAlertsCount}
            </div>
            <p className="text-xs text-slate-500 mt-1">Low stock & NCRs</p>
          </div>

          <div className="p-4 rounded-lg border border-slate-200 bg-slate-50">
            <div className="flex items-center gap-2 mb-2 text-slate-600">
              <Activity className="h-5 w-5 text-blue-500" />
              <span className="font-semibold text-sm">Active Batches</span>
            </div>
            <div className="text-2xl font-bold text-slate-900">
              {stats?.totalActiveBatches}
            </div>
            <p className="text-xs text-slate-500 mt-1">Stock {">"} 0</p>
          </div>

          <div className="p-4 rounded-lg border border-slate-200 bg-slate-50">
            <div className="flex items-center gap-2 mb-2 text-slate-600">
              <CheckCircle className="h-5 w-5 text-green-500" />
              <span className="font-semibold text-sm">Inspections</span>
            </div>
            <div className="text-2xl font-bold text-slate-900">
              {stats?.totalInspectionsConducted}
            </div>
            <p className="text-xs text-slate-500 mt-1">All time</p>
          </div>

          <div className="p-4 rounded-lg border border-slate-200 bg-slate-50">
            <div className="flex items-center gap-2 mb-2 text-slate-600">
              <Users className="h-5 w-5 text-indigo-500" />
              <span className="font-semibold text-sm">Employees</span>
            </div>
            <div className="text-2xl font-bold text-slate-900">
              {stats?.totalEmployees}
            </div>
            <p className="text-xs text-slate-500 mt-1">Total workforce</p>
          </div>
        </div>
      </div>

      {/* Main Chart Section */}
      <div className="mb-8 page-break-inside-avoid">
        <h2 className="text-xl font-bold text-slate-800 mb-4 border-b pb-2">
          Global Pass Rate Trend
        </h2>
        {/* We wrap the chart to ensure white backgrounds and standard text for printing */}
        <div className="p-4 border border-slate-200 rounded-lg bg-white h-[350px]">
          <GlobalPassRateChart data={stats?.monthlyPassRates} loading={false} />
        </div>
      </div>

      {/* Bottom Charts Section - Side by Side */}
      <div className="grid grid-cols-2 gap-8 page-break-inside-avoid">
        <div>
          <h2 className="text-xl font-bold text-slate-800 mb-4 border-b pb-2">
            Stock Distribution
          </h2>
          <div className="p-4 border border-slate-200 rounded-lg bg-white h-[350px]">
            <StockDistributionChart
              data={stats?.stockBreakdown}
              totalStock={stats?.totalStockInKg}
              loading={false}
            />
          </div>
        </div>

        <div>
          <h2 className="text-xl font-bold text-slate-800 mb-4 border-b pb-2">
            Supplier Leaderboard
          </h2>
          <div className="p-4 border border-slate-200 rounded-lg bg-white h-[350px]">
            <SupplierLeaderboardChart
              data={stats?.supplierLeaderboard}
              totalSuppliers={stats?.totalSuppliers}
              loading={false}
            />
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="mt-8 pt-4 border-t border-slate-200 text-center text-slate-500 text-sm">
        <p>BrewGuard Quality Management System - Confidential</p>
      </div>
    </div>
  );
});

AdminReportTemplate.displayName = "AdminReportTemplate";
